/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoiceTutorRouteImport } from './routes/_authenticated/voice-tutor'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedSolverRouteImport } from './routes/_authenticated/solver'
import { Route as AuthenticatedSnapSolveRouteImport } from './routes/_authenticated/snap-solve'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedPaperSolverRouteImport } from './routes/_authenticated/paper-solver'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedGraphSolverRouteImport } from './routes/_authenticated/graph-solver'
import { Route as AuthenticatedFormulasRouteImport } from './routes/_authenticated/formulas'
import { Route as AuthenticatedExamPlannerRouteImport } from './routes/_authenticated/exam-planner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyChallengeRouteImport } from './routes/_authenticated/daily-challenge'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceTutorRoute = AuthenticatedVoiceTutorRouteImport.update({
  id: '/voice-tutor',
  path: '/voice-tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolverRoute = AuthenticatedSolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSnapSolveRoute = AuthenticatedSnapSolveRouteImport.update({
  id: '/snap-solve',
  path: '/snap-solve',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaperSolverRoute =
  AuthenticatedPaperSolverRouteImport.update({
    id: '/paper-solver',
    path: '/paper-solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGraphSolverRoute =
  AuthenticatedGraphSolverRouteImport.update({
    id: '/graph-solver',
    path: '/graph-solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormulasRoute = AuthenticatedFormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamPlannerRoute =
  AuthenticatedExamPlannerRouteImport.update({
    id: '/exam-planner',
    path: '/exam-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyChallengeRoute =
  AuthenticatedDailyChallengeRouteImport.update({
    id: '/daily-challenge',
    path: '/daily-challenge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/daily-challenge': typeof AuthenticatedDailyChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-planner': typeof AuthenticatedExamPlannerRoute
  '/formulas': typeof AuthenticatedFormulasRoute
  '/graph-solver': typeof AuthenticatedGraphSolverRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/paper-solver': typeof AuthenticatedPaperSolverRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/review': typeof AuthenticatedReviewRoute
  '/snap-solve': typeof AuthenticatedSnapSolveRoute
  '/solver': typeof AuthenticatedSolverRoute
  '/study': typeof AuthenticatedStudyRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/voice-tutor': typeof AuthenticatedVoiceTutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/daily-challenge': typeof AuthenticatedDailyChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-planner': typeof AuthenticatedExamPlannerRoute
  '/formulas': typeof AuthenticatedFormulasRoute
  '/graph-solver': typeof AuthenticatedGraphSolverRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/paper-solver': typeof AuthenticatedPaperSolverRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/review': typeof AuthenticatedReviewRoute
  '/snap-solve': typeof AuthenticatedSnapSolveRoute
  '/solver': typeof AuthenticatedSolverRoute
  '/study': typeof AuthenticatedStudyRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/voice-tutor': typeof AuthenticatedVoiceTutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/daily-challenge': typeof AuthenticatedDailyChallengeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam-planner': typeof AuthenticatedExamPlannerRoute
  '/_authenticated/formulas': typeof AuthenticatedFormulasRoute
  '/_authenticated/graph-solver': typeof AuthenticatedGraphSolverRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/paper-solver': typeof AuthenticatedPaperSolverRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/snap-solve': typeof AuthenticatedSnapSolveRoute
  '/_authenticated/solver': typeof AuthenticatedSolverRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRoute
  '/_authenticated/voice-tutor': typeof AuthenticatedVoiceTutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/analytics'
    | '/bookmarks'
    | '/daily-challenge'
    | '/dashboard'
    | '/exam-planner'
    | '/formulas'
    | '/graph-solver'
    | '/leaderboard'
    | '/paper-solver'
    | '/questions'
    | '/quiz'
    | '/review'
    | '/snap-solve'
    | '/solver'
    | '/study'
    | '/topics'
    | '/voice-tutor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/analytics'
    | '/bookmarks'
    | '/daily-challenge'
    | '/dashboard'
    | '/exam-planner'
    | '/formulas'
    | '/graph-solver'
    | '/leaderboard'
    | '/paper-solver'
    | '/questions'
    | '/quiz'
    | '/review'
    | '/snap-solve'
    | '/solver'
    | '/study'
    | '/topics'
    | '/voice-tutor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/bookmarks'
    | '/_authenticated/daily-challenge'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam-planner'
    | '/_authenticated/formulas'
    | '/_authenticated/graph-solver'
    | '/_authenticated/leaderboard'
    | '/_authenticated/paper-solver'
    | '/_authenticated/questions'
    | '/_authenticated/quiz'
    | '/_authenticated/review'
    | '/_authenticated/snap-solve'
    | '/_authenticated/solver'
    | '/_authenticated/study'
    | '/_authenticated/topics'
    | '/_authenticated/voice-tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice-tutor': {
      id: '/_authenticated/voice-tutor'
      path: '/voice-tutor'
      fullPath: '/voice-tutor'
      preLoaderRoute: typeof AuthenticatedVoiceTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solver': {
      id: '/_authenticated/solver'
      path: '/solver'
      fullPath: '/solver'
      preLoaderRoute: typeof AuthenticatedSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/snap-solve': {
      id: '/_authenticated/snap-solve'
      path: '/snap-solve'
      fullPath: '/snap-solve'
      preLoaderRoute: typeof AuthenticatedSnapSolveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paper-solver': {
      id: '/_authenticated/paper-solver'
      path: '/paper-solver'
      fullPath: '/paper-solver'
      preLoaderRoute: typeof AuthenticatedPaperSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph-solver': {
      id: '/_authenticated/graph-solver'
      path: '/graph-solver'
      fullPath: '/graph-solver'
      preLoaderRoute: typeof AuthenticatedGraphSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formulas': {
      id: '/_authenticated/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof AuthenticatedFormulasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-planner': {
      id: '/_authenticated/exam-planner'
      path: '/exam-planner'
      fullPath: '/exam-planner'
      preLoaderRoute: typeof AuthenticatedExamPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-challenge': {
      id: '/_authenticated/daily-challenge'
      path: '/daily-challenge'
      fullPath: '/daily-challenge'
      preLoaderRoute: typeof AuthenticatedDailyChallengeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedDailyChallengeRoute: typeof AuthenticatedDailyChallengeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamPlannerRoute: typeof AuthenticatedExamPlannerRoute
  AuthenticatedFormulasRoute: typeof AuthenticatedFormulasRoute
  AuthenticatedGraphSolverRoute: typeof AuthenticatedGraphSolverRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPaperSolverRoute: typeof AuthenticatedPaperSolverRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSnapSolveRoute: typeof AuthenticatedSnapSolveRoute
  AuthenticatedSolverRoute: typeof AuthenticatedSolverRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRoute
  AuthenticatedVoiceTutorRoute: typeof AuthenticatedVoiceTutorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedDailyChallengeRoute: AuthenticatedDailyChallengeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamPlannerRoute: AuthenticatedExamPlannerRoute,
  AuthenticatedFormulasRoute: AuthenticatedFormulasRoute,
  AuthenticatedGraphSolverRoute: AuthenticatedGraphSolverRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPaperSolverRoute: AuthenticatedPaperSolverRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSnapSolveRoute: AuthenticatedSnapSolveRoute,
  AuthenticatedSolverRoute: AuthenticatedSolverRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRoute,
  AuthenticatedVoiceTutorRoute: AuthenticatedVoiceTutorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
