// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
    const hasSupabase = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token === 'mock-token' || !hasSupabase) {
      const mockUserId = '00000000-0000-0000-0000-000000000000';
      
      // Local JSON File Database Mock Client
      const fs = await import('fs');
      const path = await import('path');
      const DB_PATH = path.resolve(process.cwd(), 'local-db.json');

      const initDb = () => {
        if (!fs.existsSync(DB_PATH)) {
          fs.writeFileSync(DB_PATH, JSON.stringify({
            profiles: [
              {
                user_id: mockUserId,
                display_name: "Guest",
                total_points: 0,
                current_streak: 1,
                longest_streak: 1,
                last_active_date: new Date().toISOString().slice(0, 10),
                avatar_url: null
              }
            ],
            study_sessions: [],
            bookmarks: [],
            quiz_attempts: [],
            exams: [],
            topic_progress: [],
            achievements: []
          }, null, 2));
        }
      };

      const readDb = () => {
        initDb();
        try {
          return JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));
        } catch (e) {
          return {};
        }
      };

      const writeDb = (data: any) => {
        fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2));
      };

      class MockQueryPromise {
        private result: any;
        constructor(result: any) { this.result = result; }
        select() { return this; }
        single() { return this; }
        maybeSingle() { return this; }
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          return Promise.resolve(this.result).then(onfulfilled, onrejected);
        }
      }

      class MockSelectBuilder {
        private data: any[];
        private userId: string;
        private table: string;
        constructor(data: any[], userId: string, table: string) {
          this.data = [...data];
          this.userId = userId;
          this.table = table;
        }
        eq(column: string, value: any) {
          this.data = this.data.filter(row => row[column] === value);
          return this;
        }
        order(column: string, { ascending = false } = {}) {
          this.data.sort((a, b) => {
            const valA = a[column];
            const valB = b[column];
            if (valA < valB) return ascending ? -1 : 1;
            if (valA > valB) return ascending ? 1 : -1;
            return 0;
          });
          return this;
        }
        limit(count: number) {
          this.data = this.data.slice(0, count);
          return this;
        }
        single() {
          const result = { data: this.data[0] || null, error: this.data[0] ? null : { message: 'Not found' } };
          return new MockQueryPromise(result);
        }
        maybeSingle() {
          const result = { data: this.data[0] || null, error: null };
          return new MockQueryPromise(result);
        }
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          return Promise.resolve({ data: this.data, error: null }).then(onfulfilled, onrejected);
        }
      }

      class MockUpdateBuilder {
        private table: string;
        private values: any;
        private userId: string;
        private filters: Record<string, any> = {};
        constructor(table: string, values: any, userId: string) {
          this.table = table;
          this.values = values;
          this.userId = userId;
        }
        eq(column: string, value: any) {
          this.filters[column] = value;
          return this;
        }
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          const db = readDb();
          const rows = db[this.table] || [];
          let updatedCount = 0;
          for (const row of rows) {
            let matches = true;
            for (const [col, val] of Object.entries(this.filters)) {
              if (row[col] !== val) {
                matches = false;
                break;
              }
            }
            if (matches) {
              Object.assign(row, this.values);
              updatedCount++;
            }
          }
          writeDb(db);
          return Promise.resolve({ data: { count: updatedCount }, error: null }).then(onfulfilled, onrejected);
        }
      }

      class MockDeleteBuilder {
        private table: string;
        private userId: string;
        private filters: Record<string, any> = {};
        constructor(table: string, userId: string) {
          this.table = table;
          this.userId = userId;
        }
        eq(column: string, value: any) {
          this.filters[column] = value;
          return this;
        }
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          const db = readDb();
          const beforeLength = db[this.table]?.length || 0;
          if (db[this.table]) {
            db[this.table] = db[this.table].filter((row: any) => {
              let matches = true;
              for (const [col, val] of Object.entries(this.filters)) {
                if (row[col] !== val) {
                  matches = false;
                  break;
                }
              }
              return !matches;
            });
          }
          writeDb(db);
          const deletedCount = beforeLength - (db[this.table]?.length || 0);
          return Promise.resolve({ data: { count: deletedCount }, error: null }).then(onfulfilled, onrejected);
        }
      }

      class MockClient {
        private userId: string;
        constructor(userId: string) { this.userId = userId; }
        from(table: string) {
          const userId = this.userId;
          return {
            insert(row: any) {
              const db = readDb();
              if (!db[table]) db[table] = [];
              const rows = Array.isArray(row) ? row : [row];
              const inserted: any[] = [];
              
              const generateUUID = () => {
                return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
                  const r = Math.random() * 16 | 0;
                  const v = c === 'x' ? r : (r & 0x3 | 0x8);
                  return v.toString(16);
                });
              };

              for (const r of rows) {
                const newRow = {
                  id: generateUUID(),
                  created_at: new Date().toISOString(),
                  ...r,
                };
                db[table].push(newRow);
                inserted.push(newRow);
              }
              writeDb(db);
              const result = { data: Array.isArray(row) ? inserted : inserted[0], error: null };
              return new MockQueryPromise(result);
            },
            select(columns = '*') {
              const db = readDb();
              const data = db[table] || [];
              return new MockSelectBuilder(data, userId, table);
            },
            update(values: any) {
              return new MockUpdateBuilder(table, values, userId);
            },
            delete() {
              return new MockDeleteBuilder(table, userId);
            }
          };
        }
        get rpc() { return undefined; }
      }

      const mockClient = new MockClient(mockUserId);
      return next({
        context: {
          supabase: mockClient as any,
          userId: mockUserId,
          claims: { sub: mockUserId } as any,
        },
      });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
